import { CatViewerImageType } from "@types";

export const DEFAULT_IMAGES: CatViewerImageType[] = [
  {
    breeds: [],
    categories: [
      {
        id: 7,
        name: "ties",
      },
    ],
    id: "10j",
    url: "https://cdn2.thecatapi.com/images/10j.jpg",
    width: 500,
    height: 335,
  },
  {
    breeds: [],
    id: "1js",
    url: "https://cdn2.thecatapi.com/images/1js.jpg",
    width: 500,
    height: 334,
  },
  {
    breeds: [],
    categories: [
      {
        id: 9,
        name: "dream",
      },
    ],
    id: "1pd",
    url: "https://cdn2.thecatapi.com/images/1pd.jpg",
    width: 640,
    height: 434,
  },
  {
    breeds: [],
    categories: [
      {
        id: 9,
        name: "dream",
      },
    ],
    id: "1qv",
    url: "https://cdn2.thecatapi.com/images/1qv.jpg",
    width: 500,
    height: 333,
  },
  {
    breeds: [],
    id: "3hd",
    url: "https://cdn2.thecatapi.com/images/3hd.jpg",
    width: 640,
    height: 396,
  },
  {
    breeds: [],
    categories: [
      {
        id: 6,
        name: "caturday",
      },
    ],
    id: "416",
    url: "https://cdn2.thecatapi.com/images/416.jpg",
    width: 419,
    height: 500,
  },
  {
    breeds: [],
    id: "abn",
    url: "https://cdn2.thecatapi.com/images/abn.jpg",
    width: 800,
    height: 533,
  },
  {
    breeds: [],
    id: "ag6",
    url: "https://cdn2.thecatapi.com/images/ag6.png",
    width: 1024,
    height: 1024,
  },
  {
    breeds: [],
    id: "ap5",
    url: "https://cdn2.thecatapi.com/images/ap5.jpg",
    width: 480,
    height: 360,
  },
  {
    breeds: [],
    id: "avg",
    url: "https://cdn2.thecatapi.com/images/avg.jpg",
    width: 604,
    height: 483,
  },
  {
    breeds: [],
    id: "b1u",
    url: "https://cdn2.thecatapi.com/images/b1u.jpg",
    width: 612,
    height: 612,
  },
  {
    breeds: [],
    id: "b2t",
    url: "https://cdn2.thecatapi.com/images/b2t.jpg",
    width: 3440,
    height: 4263,
  },
  {
    breeds: [],
    id: "bc6",
    url: "https://cdn2.thecatapi.com/images/bc6.jpg",
    width: 500,
    height: 341,
  },
  {
    breeds: [],
    id: "be1",
    url: "https://cdn2.thecatapi.com/images/be1.jpg",
    width: 500,
    height: 477,
  },
  {
    breeds: [],
    id: "beq",
    url: "https://cdn2.thecatapi.com/images/beq.jpg",
    width: 500,
    height: 333,
  },
  {
    breeds: [],
    id: "cce",
    url: "https://cdn2.thecatapi.com/images/cce.jpg",
    width: 800,
    height: 1067,
  },
  {
    breeds: [],
    id: "MTk5NTUzNA",
    url: "https://cdn2.thecatapi.com/images/MTk5NTUzNA.jpg",
    width: 760,
    height: 884,
  },
  {
    breeds: [
      {
        weight: {
          imperial: "6 - 15",
          metric: "3 - 7",
        },
        id: "birm",
        name: "Birman",
        cfa_url: "http://cfa.org/Breeds/BreedsAB/Birman.aspx",
        vetstreet_url: "http://www.vetstreet.com/cats/birman",
        vcahospitals_url: "https://vcahospitals.com/know-your-pet/cat-breeds/birman",
        temperament: "Affectionate, Active, Gentle, Social",
        origin: "France",
        country_codes: "FR",
        country_code: "FR",
        description:
          "The Birman is a docile, quiet cat who loves people and will follow them from room to room. Expect the Birman to want to be involved in what you’re doing. He communicates in a soft voice, mainly to remind you that perhaps it’s time for dinner or maybe for a nice cuddle on the sofa. He enjoys being held and will relax in your arms like a furry baby.",
        life_span: "14 - 15",
        indoor: 0,
        lap: 1,
        alt_names: "Sacred Birman, Sacred Cat Of Burma",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 3,
        grooming: 2,
        health_issues: 1,
        intelligence: 3,
        shedding_level: 3,
        social_needs: 4,
        stranger_friendly: 3,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Birman",
        hypoallergenic: 0,
        reference_image_id: "HOrX5gwLS",
      },
    ],
    id: "OhTkBTPnD",
    url: "https://cdn2.thecatapi.com/images/OhTkBTPnD.jpg",
    width: 1100,
    height: 1100,
  },
  {
    breeds: [
      {
        weight: {
          imperial: "6 - 10",
          metric: "3 - 5",
        },
        id: "lape",
        name: "LaPerm",
        cfa_url: "http://cfa.org/Breeds/BreedsKthruR/LaPerm.aspx",
        vetstreet_url: "http://www.vetstreet.com/cats/laperm",
        vcahospitals_url: "https://vcahospitals.com/know-your-pet/cat-breeds/laperm",
        temperament: "Affectionate, Friendly, Gentle, Intelligent, Playful, Quiet",
        origin: "Thailand",
        country_codes: "TH",
        country_code: "TH",
        description:
          "LaPerms are gentle and affectionate but also very active. Unlike many active breeds, the LaPerm is also quite content to be a lap cat. The LaPerm will often follow your lead; that is, if they are busy playing and you decide to sit and relax, simply pick up your LaPerm and sit down with it, and it will stay in your lap, devouring the attention you give it.",
        life_span: "10 - 15",
        indoor: 0,
        lap: 1,
        alt_names: "Si-Sawat",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 4,
        grooming: 1,
        health_issues: 1,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 4,
        stranger_friendly: 4,
        vocalisation: 3,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 1,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/LaPerm",
        hypoallergenic: 1,
        reference_image_id: "aKbsEYjSl",
      },
    ],
    id: "-d7GY-cPZ",
    url: "https://cdn2.thecatapi.com/images/-d7GY-cPZ.jpg",
    width: 1024,
    height: 768,
  },
  {
    breeds: [
      {
        weight: {
          imperial: "5 - 10",
          metric: "2 - 5",
        },
        id: "tang",
        name: "Turkish Angora",
        cfa_url: "http://cfa.org/Breeds/BreedsSthruT/TurkishAngora.aspx",
        vetstreet_url: "http://www.vetstreet.com/cats/turkish-angora",
        vcahospitals_url: "https://vcahospitals.com/know-your-pet/cat-breeds/turkish-angora",
        temperament: "Affectionate, Agile, Clever, Gentle, Intelligent, Playful, Social",
        origin: "Turkey",
        country_codes: "TR",
        country_code: "TR",
        description:
          "This is a smart and intelligent cat which bonds well with humans. With its affectionate and playful personality the Angora is a top choice for families. The Angora gets along great with other pets in the home, but it will make clear who is in charge, and who the house belongs to",
        life_span: "15 - 18",
        indoor: 0,
        alt_names: "Ankara",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 5,
        grooming: 2,
        health_issues: 2,
        intelligence: 5,
        shedding_level: 2,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 3,
        experimental: 0,
        hairless: 0,
        natural: 1,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Turkish_Angora",
        hypoallergenic: 0,
        reference_image_id: "7CGV6WVXq",
      },
    ],
    id: "ZGoY_Ivly",
    url: "https://cdn2.thecatapi.com/images/ZGoY_Ivly.jpg",
    width: 1600,
    height: 1200,
  },
];
